### ISSUE TITLE
Bemi migration leads to syntax error

### ISSUE THREAD

**Issue by jordan-with-power** [BemiHQ/bemi-prisma#2]
I'm running into an error when trying to run `npx prisma migrate dev` to apply the Bemi-generated migration.

```
Error: P3006

Migration `20240104202237_bemi` failed to apply cleanly to the shadow database. 
Error:
ERROR: syntax error at or near ""ClinicalTrialCollaborator""
   0: sql_schema_connector::validate_migrations
           with namespaces=None
             at schema-engine/connectors/sql-schema-connector/src/lib.rs:324
   1: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:270
```

Running `PostgreSQL 14.10` locally.

**Comment by exAspArk** [comment]
Hi @jordan-with-power – thanks for submitting this issue!

I just released a fix. Can you try to:

* Install the latest `@bemi-db/prisma` version 0.2.1
* Remove the `20240104202237_bemi` migration directory
* Execute `npx bemi migration:create` and run the migration again

Let me know if you have any questions!

Also, feel free to join [our Discord](https://discord.gg/mXeZ6w2tGf) to discuss any issues while having faster feedback loops.
